// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhXXUQf5Xsk6Fg2XtEsVU3reH7_akAwes',
    appId: '1:629245277294:web:4db1a31182f1d97588e27f',
    messagingSenderId: '629245277294',
    projectId: 'hoptok-addff',
    authDomain: 'hoptok-addff.firebaseapp.com',
    storageBucket: 'hoptok-addff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWt4enLgsVqVZykg7BbOnwTRxxcsNs7Ts',
    appId: '1:629245277294:android:11e2b901f770c67d88e27f',
    messagingSenderId: '629245277294',
    projectId: 'hoptok-addff',
    storageBucket: 'hoptok-addff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyILpWb08hq0ll00sy4pXxYPKXGznUUc',
    appId: '1:629245277294:ios:57ce0fcef95b952788e27f',
    messagingSenderId: '629245277294',
    projectId: 'hoptok-addff',
    storageBucket: 'hoptok-addff.appspot.com',
    iosBundleId: 'com.example.hopTock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyILpWb08hq0ll00sy4pXxYPKXGznUUc',
    appId: '1:629245277294:ios:bea69e89834f412488e27f',
    messagingSenderId: '629245277294',
    projectId: 'hoptok-addff',
    storageBucket: 'hoptok-addff.appspot.com',
    iosBundleId: 'com.example.hopTock.RunnerTests',
  );
}
